export const cie10Data = [
  // RESPIRATORIO / INFECCIOSO
  { codigo: "J00", descripcion: "Nasofaringitis aguda (resfriado común)", grupo: "Respiratorio / Infeccioso",
    sistema: "Respiratorio", tipo: "agudo" },
  { codigo: "J02.9", descripcion: "Faringitis aguda, no especificada", grupo: "Respiratorio / Infeccioso",
    sistema: "Respiratorio", tipo: "agudo" },
  { codigo: "J03.9", descripcion: "Amigdalitis aguda, no especificada", grupo: "Respiratorio / Infeccioso",
    sistema: "Respiratorio", tipo: "agudo" },
  { codigo: "J06.9", descripcion: "Infección aguda de vías respiratorias superiores, no especificada", grupo: "Respiratorio / Infeccioso",
    sistema: "Respiratorio", tipo: "agudo" },
  { codigo: "J18.9", descripcion: "Neumonía, organismo no especificado", grupo: "Respiratorio / Infeccioso",
    sistema: "Respiratorio", tipo: "agudo" },
  { codigo: "J20.9", descripcion: "Bronquitis aguda, no especificada", grupo: "Respiratorio / Infeccioso",
    sistema: "Respiratorio", tipo: "agudo" },
  { codigo: "J21.9", descripcion: "Bronquiolitis aguda, no especificada", grupo: "Respiratorio / Infeccioso (pediatría)",
    sistema: "Respiratorio", tipo: "agudo" },
  { codigo: "J45.909", descripcion: "Asma, no especificada, no complicada", grupo: "Respiratorio crónico",
    sistema: "Respiratorio", tipo: "crónico" },
  { codigo: "U07.1", descripcion: "COVID-19, virus identificado", grupo: "Respiratorio / Infeccioso",
    sistema: "Respiratorio", tipo: "agudo" },

  // CARDIOVASCULAR
  { codigo: "I10", descripcion: "Hipertensión esencial (primaria)", grupo: "Cardiovascular",
    sistema: "Cardiovascular", tipo: "crónico" },
  { codigo: "I20.9", descripcion: "Angina de pecho, no especificada", grupo: "Cardiovascular",
    sistema: "Cardiovascular", tipo: "crónico" },
  { codigo: "I25.10", descripcion: "Cardiopatía isquémica crónica sin angina", grupo: "Cardiovascular",
    sistema: "Cardiovascular", tipo: "crónico" },
  { codigo: "I50.9", descripcion: "Insuficiencia cardiaca, no especificada", grupo: "Cardiovascular",
    sistema: "Cardiovascular", tipo: "crónico" },

  // METABÓLICO / ENDOCRINO
  { codigo: "E11.9", descripcion: "Diabetes mellitus tipo 2 sin complicaciones", grupo: "Metabólico / Endocrino",
    sistema: "Metabólico", tipo: "crónico" },
  { codigo: "E10.9", descripcion: "Diabetes mellitus tipo 1 sin complicaciones", grupo: "Metabólico / Endocrino",
    sistema: "Metabólico", tipo: "crónico" },
  { codigo: "E78.5", descripcion: "Hiperlipidemia, no especificada", grupo: "Metabólico / Endocrino",
    sistema: "Metabólico", tipo: "crónico" },
  { codigo: "E03.9", descripcion: "Hipotiroidismo, no especificado", grupo: "Metabólico / Endocrino",
    sistema: "Metabólico", tipo: "crónico" },
  { codigo: "E55.9", descripcion: "Deficiencia de vitamina D, no especificada", grupo: "Metabólico / Nutrición",
    sistema: "Metabólico", tipo: "crónico" },
  { codigo: "E66.9", descripcion: "Obesidad, no especificada", grupo: "Metabólico / Nutrición",
    sistema: "Metabólico", tipo: "crónico" },

  // DIGESTIVO / INFECCIOSO
  { codigo: "A09.9", descripcion: "Gastroenteritis y colitis infecciosa, no especificada", grupo: "Digestivo / Infeccioso",
    sistema: "Digestivo", tipo: "agudo" },
  { codigo: "K52.9", descripcion: "Gastroenteritis y colitis no infecciosa, no especificada", grupo: "Digestivo",
    sistema: "Digestivo", tipo: "agudo" },
  { codigo: "K21.9", descripcion: "Enfermedad por reflujo gastroesofágico sin esofagitis", grupo: "Digestivo",
    sistema: "Digestivo", tipo: "crónico" },
  { codigo: "R10.9", descripcion: "Dolor abdominal, no especificado", grupo: "Digestivo / Síntomas",
    sistema: "Digestivo", tipo: "síntoma" },

  // MUSCULO-ESQUELÉTICO
  { codigo: "M54.50", descripcion: "Lumbalgia baja, no especificada", grupo: "Músculo-esquelético / Columna",
    sistema: "Músculo-esquelético", tipo: "agudo" },
  { codigo: "M54.2", descripcion: "Cervicalgia (dolor de cuello)", grupo: "Músculo-esquelético / Columna",
    sistema: "Músculo-esquelético", tipo: "agudo" },
  { codigo: "M79.60", descripcion: "Dolor en extremidad, no especificado", grupo: "Músculo-esquelético",
    sistema: "Músculo-esquelético", tipo: "síntoma" },

  // GENITOURINARIO / ITU
  { codigo: "N39.0", descripcion: "Infección del tracto urinario, sitio no especificado", grupo: "Genitourinario / ITU",
    sistema: "Genitourinario", tipo: "agudo" },
  { codigo: "N30.00", descripcion: "Cistitis aguda sin hematuria", grupo: "Genitourinario / ITU baja",
    sistema: "Genitourinario", tipo: "agudo" },
  { codigo: "N10", descripcion: "Pielonefritis aguda", grupo: "Genitourinario / ITU alta",
    sistema: "Genitourinario", tipo: "agudo" },
  { codigo: "N40.1", descripcion: "Hiperplasia benigna de próstata con síntomas urinarios", grupo: "Genitourinario / Próstata",
    sistema: "Genitourinario", tipo: "crónico" },

  // GINECOLOGÍA / OBSTETRICIA (resumen)
  { codigo: "N76.0", descripcion: "Vaginitis aguda", grupo: "Ginecología / Infeccioso",
    sistema: "Ginecología", tipo: "agudo" },
  { codigo: "B37.3", descripcion: "Candidiasis vulvovaginal", grupo: "Ginecología / Infeccioso",
    sistema: "Ginecología", tipo: "agudo" },
  { codigo: "N92.0", descripcion: "Menstruación excesiva y frecuente, regular", grupo: "Ginecología / Sangrado anormal",
    sistema: "Ginecología", tipo: "crónico" },
  { codigo: "N91.2", descripcion: "Amenorrea secundaria, no especificada", grupo: "Ginecología / Menstruación",
    sistema: "Ginecología", tipo: "crónico" },
  { codigo: "D25.9", descripcion: "Leiomioma del útero, no especificado (miomatosis)", grupo: "Ginecología / Útero",
    sistema: "Ginecología", tipo: "crónico" },
  { codigo: "Z34.8", descripcion: "Vigilancia de otros embarazos normales", grupo: "Obstetricia / Control prenatal",
    sistema: "Ginecología", tipo: "prevención" },
  { codigo: "O20.0", descripcion: "Amenaza de aborto", grupo: "Obstetricia / Aborto temprano",
    sistema: "Ginecología", tipo: "agudo" },

  // PSIQUIATRÍA
  { codigo: "F32.9", descripcion: "Episodio depresivo, no especificado", grupo: "Salud mental / Depresión",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F33.9", descripcion: "Trastorno depresivo recurrente, no especificado", grupo: "Salud mental / Depresión",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F41.1", descripcion: "Trastorno de ansiedad generalizada", grupo: "Salud mental / Ansiedad",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F41.9", descripcion: "Trastorno de ansiedad, no especificado", grupo: "Salud mental / Ansiedad",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F43.20", descripcion: "Trastorno de adaptación, no especificado", grupo: "Salud mental / Adaptación",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F10.20", descripcion: "Trastorno por consumo de alcohol, dependencia, no complicado", grupo: "Salud mental / Sustancias",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F17.210", descripcion: "Dependencia de nicotina, cigarrillos, no complicada", grupo: "Salud mental / Sustancias",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F20.0", descripcion: "Esquizofrenia paranoide", grupo: "Salud mental / Psicosis",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F23.9", descripcion: "Psicosis aguda y transitoria, no especificada", grupo: "Salud mental / Psicosis aguda",
    sistema: "Salud mental", tipo: "agudo" },
  { codigo: "F51.0", descripcion: "Insomnio no orgánico", grupo: "Salud mental / Sueño",
    sistema: "Salud mental", tipo: "crónico" },
  { codigo: "F03.9", descripcion: "Demencia, no especificada", grupo: "Salud mental / Neurocognitivo",
    sistema: "Salud mental", tipo: "crónico" },

  // INFECCIOSO SISTÉMICO / SEPSIS
  { codigo: "A41.9", descripcion: "Sepsis, no especificada", grupo: "Infeccioso sistémico / Sepsis",
    sistema: "Síntomas generales", tipo: "agudo" },

  // SÍNTOMAS GENERALES / PREVENCIÓN
  { codigo: "R07.9", descripcion: "Dolor torácico, no especificado", grupo: "Síntomas generales / Cardiopulmonar",
    sistema: "Síntomas generales", tipo: "síntoma" },
  { codigo: "R50.9", descripcion: "Fiebre, no especificada", grupo: "Síntomas generales",
    sistema: "Síntomas generales", tipo: "síntoma" },
  { codigo: "Z00.00", descripcion: "Examen médico general de adulto, sin hallazgos anormales", grupo: "Prevención",
    sistema: "Prevención", tipo: "prevención" },
  { codigo: "Z23", descripcion: "Encuentro para inmunización", grupo: "Prevención",
    sistema: "Prevención", tipo: "prevención" }
];

/* ========= CATALOGO DE MEDICAMENTOS (incluye psiquiátricos, ATC, dosisMg) ========= */

export const medicamentosData = [
  // Analgésicos / AINE orales
  { dci: "Paracetamol", presentacion: "500 mg tabletas", via: "Vía oral",
    grupo: "Analgésico / Antipirético",
    atc: "N02BE01",
    dosisMg: 500,
    marcas: ["Panadol","Tylenol","Genérico"] },
  { dci: "Ibuprofeno", presentacion: "400 mg tabletas", via: "Vía oral",
    grupo: "AINE",
    atc: "M01AE01",
    dosisMg: 400,
    marcas: ["Advil","Motrin","Genérico","Dolofén"] },

  // Antibiótico ejemplo
  { dci: "Amoxicilina", presentacion: "500 mg cápsulas", via: "Vía oral",
    grupo: "Penicilina de amplio espectro",
    atc: "J01CA04",
    dosisMg: 500,
    marcas: ["Velamox","Clamoxin","Genérico"] },

  // Respiratorio
  { dci: "Salbutamol", presentacion: "Inhalador 100 mcg/dosis", via: "Inhalatoria",
    grupo: "Broncodilatador beta-2",
    atc: "R03AC02",
    marcas: ["Ventolin","Aerolin","Salburex"] },

  // Cardiometabólicos
  { dci: "Losartán", presentacion: "50 mg tabletas", via: "Vía oral",
    grupo: "Antihipertensivo (ARA-II)",
    atc: "C09CA01",
    dosisMg: 50,
    marcas: ["Cozaar","Losapress","Genérico"] },
  { dci: "Metformina", presentacion: "850 mg tabletas", via: "Vía oral",
    grupo: "Biguanida",
    atc: "A10BA02",
    dosisMg: 850,
    marcas: ["Glucophage","Metforal","Genérico"] },

  /* PSIQUIÁTRICOS – Antidepresivos ISRS */
  { dci: "Fluoxetina", presentacion: "20 mg cápsulas", via: "Vía oral",
    grupo: "Antidepresivo ISRS",
    atc: "N06AB03",
    dosisMg: 20,
    marcas: ["Prozac","Fluxan","Genérico"] },
  { dci: "Sertralina", presentacion: "50 mg tabletas", via: "Vía oral",
    grupo: "Antidepresivo ISRS",
    atc: "N06AB06",
    dosisMg: 50,
    marcas: ["Zoloft","Genérico"] },
  { dci: "Citalopram", presentacion: "20 mg tabletas", via: "Vía oral",
    grupo: "Antidepresivo ISRS",
    atc: "N06AB04",
    dosisMg: 20,
    marcas: ["Celexa","Genérico"] },

  /* ISRN / Otros AD */
  { dci: "Venlafaxina", presentacion: "75 mg cápsulas LP", via: "Vía oral",
    grupo: "Antidepresivo ISRN",
    atc: "N06AX16",
    dosisMg: 75,
    marcas: ["Effexor XR","Genérico"] },
  { dci: "Duloxetina", presentacion: "60 mg cápsulas", via: "Vía oral",
    grupo: "Antidepresivo ISRN",
    atc: "N06AX21",
    dosisMg: 60,
    marcas: ["Cymbalta","Genérico"] },
  { dci: "Mirtazapina", presentacion: "30 mg tabletas", via: "Vía oral",
    grupo: "Antidepresivo NaSSA",
    atc: "N06AX11",
    dosisMg: 30,
    marcas: ["Remeron","Genérico"] },
  { dci: "Amitriptilina", presentacion: "25 mg tabletas", via: "Vía oral",
    grupo: "Antidepresivo tricíclico",
    atc: "N06AA09",
    dosisMg: 25,
    marcas: ["Tryptanol","Genérico"] },

  /* Ansiolíticos / Benzodiacepinas */
  { dci: "Diazepam", presentacion: "5 mg tabletas", via: "Vía oral",
    grupo: "Benzodiacepina (ansiolítico / sedante)",
    atc: "N05BA01",
    dosisMg: 5,
    marcas: ["Valium","Genérico"] },
  { dci: "Alprazolam", presentacion: "0.5 mg tabletas", via: "Vía oral",
    grupo: "Benzodiacepina (ansiolítico)",
    atc: "N05BA12",
    dosisMg: 0.5,
    marcas: ["Xanax","Tafil","Genérico"] },
  { dci: "Clonazepam", presentacion: "0.5 mg tabletas", via: "Vía oral",
    grupo: "Benzodiacepina (ansiolítico / anticonvulsivante)",
    atc: "N03AE01",
    dosisMg: 0.5,
    marcas: ["Rivotril","Genérico"] },
  { dci: "Buspirona", presentacion: "10 mg tabletas", via: "Vía oral",
    grupo: "Ansiolítico no benzodiacepínico",
    atc: "N05BE01",
    dosisMg: 10,
    marcas: ["Buspar","Genérico"] },

  /* Estabilizadores del ánimo */
  { dci: "Carbonato de litio", presentacion: "300 mg tabletas", via: "Vía oral",
    grupo: "Estabilizador del ánimo",
    atc: "N05AN01",
    dosisMg: 300,
    marcas: ["Lithobid","Genérico"] },
  { dci: "Valproato de sodio", presentacion: "500 mg tabletas LP", via: "Vía oral",
    grupo: "Antiepiléptico / estabilizador del ánimo",
    atc: "N03AG01",
    dosisMg: 500,
    marcas: ["Depakote","Genérico"] },

  /* Antipsicóticos típicos y atípicos */
  { dci: "Haloperidol", presentacion: "5 mg tabletas", via: "Vía oral",
    grupo: "Antipsicótico típico",
    atc: "N05AD01",
    dosisMg: 5,
    marcas: ["Haldol","Genérico"] },
  { dci: "Risperidona", presentacion: "2 mg tabletas", via: "Vía oral",
    grupo: "Antipsicótico atípico",
    atc: "N05AX08",
    dosisMg: 2,
    marcas: ["Risperdal","Genérico"] },
  { dci: "Quetiapina", presentacion: "100 mg tabletas", via: "Vía oral",
    grupo: "Antipsicótico atípico",
    atc: "N05AH04",
    dosisMg: 100,
    marcas: ["Seroquel","Genérico"] },
  { dci: "Olanzapina", presentacion: "10 mg tabletas", via: "Vía oral",
    grupo: "Antipsicótico atípico",
    atc: "N05AH03",
    dosisMg: 10,
    marcas: ["Zyprexa","Genérico"] }
];

/* ========= CATALOGO DE EXÁMENES (incluye infecciones) ========= */

export const examenesCatalogo = [
  // Infecciones respiratorias
  { nombre: "Hemograma completo (CBC)", tipo: "Laboratorio", grupo: "Hematología / Infeccioso",
    indicacionesSug: "Ayuno no estricto; valorar leucocitosis y respuesta inflamatoria." },
  { nombre: "Proteína C reactiva (PCR)", tipo: "Laboratorio", grupo: "Inflamación / Infeccioso",
    indicacionesSug: "Ayuno no estricto; útil para diferenciar infección bacteriana de viral." },
  { nombre: "Velocidad de sedimentación globular (VSG)", tipo: "Laboratorio", grupo: "Inflamación / Infeccioso",
    indicacionesSug: "Ayuno relativo; interpretar junto a clínica y otros marcadores." },
  { nombre: "Hisopado nasofaríngeo para panel respiratorio (PCR)", tipo: "Laboratorio", grupo: "Respiratorio / Infeccioso",
    indicacionesSug: "Tomar antes de antivirales; técnica adecuada de hisopado." },
  { nombre: "Hisopado nasofaríngeo para SARS-CoV-2 (PCR/antígeno)", tipo: "Laboratorio", grupo: "Respiratorio / Infeccioso",
    indicacionesSug: "Tomar en fase aguda; no requiere ayuno; usar EPP." },

  // ITU
  { nombre: "Examen completo de orina (EGO)", tipo: "Laboratorio", grupo: "Urinario / Infeccioso",
    indicacionesSug: "Orina de chorro medio, primera de la mañana, higiene previa." },
  { nombre: "Urocultivo con antibiograma", tipo: "Laboratorio", grupo: "Urinario / Infeccioso",
    indicacionesSug: "Antes de antibiótico o tras suspensión; muestra estéril de chorro medio." },
  { nombre: "Nitrógeno ureico (BUN) y creatinina sérica", tipo: "Laboratorio", grupo: "Metabolismo / Riñón",
    indicacionesSug: "Ayuno relativo; valorar función renal en ITU complicada o sepsis." },

  // Gastrointestinal infeccioso
  { nombre: "Coprocultivo con antibiograma", tipo: "Laboratorio", grupo: "Digestivo / Infeccioso",
    indicacionesSug: "Heces frescas; diarrea con fiebre, sangre o prolongada." },
  { nombre: "Parasitológico seriado de heces (3 muestras)", tipo: "Laboratorio", grupo: "Digestivo / Infeccioso",
    indicacionesSug: "Recolectar en días alternos; evitar laxantes y contraste baritado." },
  { nombre: "Toxina de Clostridioides difficile en heces", tipo: "Laboratorio", grupo: "Digestivo / Infeccioso",
    indicacionesSug: "Diarrea asociada a antibióticos u hospitalización; no heces formadas." },

  // Piel y partes blandas
  { nombre: "Cultivo de exudado de piel y partes blandas con antibiograma", tipo: "Laboratorio", grupo: "Dermatología / Infeccioso",
    indicacionesSug: "Tomar de fondo de la lesión tras limpieza suave." },
  { nombre: "Tinción de Gram de exudado", tipo: "Laboratorio", grupo: "Dermatología / Infeccioso",
    indicacionesSug: "Orientar germen (Gram+ vs Gram-) para terapia empírica." },

  // Sepsis
  { nombre: "Hemocultivos seriados (2–3 pares)", tipo: "Laboratorio", grupo: "Infeccioso sistémico / Sepsis",
    indicacionesSug: "Antes de antibiótico, sitios y tiempos distintos, técnica aséptica." },
  { nombre: "Lactato sérico", tipo: "Laboratorio", grupo: "Infeccioso sistémico / Sepsis",
    indicacionesSug: "Fundamental en valoración de sepsis y choque séptico." },
  { nombre: "Perfil metabólico básico (BMP)", tipo: "Laboratorio", grupo: "Metabolismo / Infeccioso sistémico",
    indicacionesSug: "Ayuno 8 h; electrolitos y función renal." },
  { nombre: "Gasometría arterial o venosa", tipo: "Laboratorio", grupo: "Infeccioso sistémico / Crítico",
    indicacionesSug: "Pacientes con compromiso respiratorio o hemodinámico." }
];
