import test from "node:test";
import assert from "node:assert/strict";
import { cie10Data, medicamentosData, examenesCatalogo } from "../catalogos.js";

test("los catálogos conservan el tamaño de la versión anterior", () => {
  assert.ok(cie10Data.length >= 2300);
  assert.ok(medicamentosData.length >= 900);
  assert.ok(examenesCatalogo.length >= 150);
  assert.ok(medicamentosData.some((med) => med.dci === "Omeprazol"));
  assert.ok(medicamentosData.some((med) => med.dci === "Diclofenaco sódico" && /ampolla IM/.test(med.presentacion)));
  assert.ok(medicamentosData.some((med) => med.dci === "Diclofenaco sódico" && /ampolla IV/.test(med.presentacion)));
  assert.ok(medicamentosData.some((med) => med.dci === "Ketoprofeno" && /ampolla IM/.test(med.presentacion)));
  assert.ok(medicamentosData.some((med) => med.dci === "Clonixinato de lisina" && /ampolla IM/.test(med.presentacion)));
  assert.ok(medicamentosData.some((med) => med.dci === "Clorfenamina" && /ampolla IM/.test(med.presentacion)));
  assert.ok(examenesCatalogo.some((ex) => ex.nombre === "Mamografía bilateral"));
  assert.ok(cie10Data.some((dx) => dx.codigo === "I10"));
  assert.equal(cie10Data.every((dx) => dx.tipo && dx.subtipo && dx.sistema), true);
  assert.equal(cie10Data.some((dx) => dx.tipo === "otro"), false);
  const porCodigo = new Map(cie10Data.map((dx) => [dx.codigo, dx]));
  assert.equal(porCodigo.get("K29.1").tipo, "agudo");
  assert.equal(porCodigo.get("K29.5").tipo, "crónico");
  assert.equal(porCodigo.get("K25.4").tipo, "crónico");
  assert.equal(porCodigo.get("N30.2").tipo, "crónico");
  assert.equal(porCodigo.get("N70.1").sistema, "Ginecología");
  assert.equal(porCodigo.get("J42").tipo, "crónico");
  assert.equal(porCodigo.get("I10").subtipo, "hipertensivo");
  assert.equal(porCodigo.get("J45.9").subtipo, "asmático");
  assert.equal(porCodigo.get("J45.1").subtipo, "asmático");
  assert.equal(porCodigo.get("K80.2").subtipo, "biliar");
  assert.equal(porCodigo.get("K29.00").subtipo, "gástrico");
  assert.equal(porCodigo.get("K29.0").subtipo, "hemorrágico");
  assert.equal(porCodigo.get("E11.9").subtipo, "diabetes");
  assert.equal(porCodigo.get("N18.3").severidad, "estadio 3");
  assert.equal(porCodigo.get("O82").tipo, "agudo");
  assert.equal(porCodigo.get("A97.0").subtipo, "dengue");
  assert.equal(porCodigo.get("F32.2").severidad, "grave");
  assert.equal(new Set(cie10Data.map((dx) => dx.codigo)).size, cie10Data.length);
  assert.equal(porCodigo.get("J14").subtipo, "neumonía");
  assert.equal(porCodigo.get("J15.4").subtipo, "neumonía");
  assert.equal(porCodigo.get("J18.8").descripcion, "Otras neumonías de microorganismo no especificado");
  assert.equal(porCodigo.get("J12.82").descripcion, "Neumonía por COVID-19");
  assert.match(porCodigo.get("A48.1").descripcion, /Neumonía por Legionella/);
  assert.match(porCodigo.get("J18.9").alias, /comunitaria/);
  assert.match(porCodigo.get("I10").alias, /hta/);
  assert.match(porCodigo.get("E11.9").alias, /dm2/);
  assert.ok(cie10Data.filter((dx) => /neumon/i.test(`${dx.descripcion} ${dx.alias || ""}`)).length >= 45);
  assert.equal(porCodigo.get("J45.21").tipo, "agudo");
  assert.equal(porCodigo.get("E11.65").subtipo, "diabetes");
  assert.equal(porCodigo.get("N18.31").severidad, "estadio 3a");
});
