export const VARIANTES = [
  ["J12.81", "Neumonía por coronavirus asociado al SARS", "Respiratorio"],
  ["J12.82", "Neumonía por COVID-19", "Respiratorio"],
  ["J12.89", "Otra neumonía viral", "Respiratorio"],
  ["J15.4", "Neumonía por otros estreptococos", "Respiratorio"],
  ["J15.6", "Neumonía por otras bacterias gramnegativas", "Respiratorio"],
  ["J15.8", "Otras neumonías bacterianas", "Respiratorio"],
  ["J16.8", "Neumonía por otros microorganismos infecciosos especificados", "Respiratorio"],
  ["J17", "Neumonía en enfermedades clasificadas en otra parte", "Respiratorio"],
  ["J18.8", "Otras neumonías de microorganismo no especificado", "Respiratorio"],
  ["P23.0", "Neumonía congénita por virus", "Perinatal"],
  ["P23.1", "Neumonía congénita por clamidia", "Perinatal"],
  ["P23.2", "Neumonía congénita por estafilococo", "Perinatal"],
  ["P23.3", "Neumonía congénita por estreptococo del grupo B", "Perinatal"],
  ["P23.4", "Neumonía congénita por Escherichia coli", "Perinatal"],
  ["P23.5", "Neumonía congénita por Pseudomonas", "Perinatal"],
  ["P23.6", "Neumonía congénita por otras bacterias", "Perinatal"],
  ["P23.8", "Neumonía congénita por otros organismos", "Perinatal"],
  ["J69.1", "Neumonía por aspiración de aceites y esencias", "Respiratorio"],
  ["J69.8", "Neumonía por aspiración de otros sólidos y líquidos", "Respiratorio"],
  ["J85.0", "Gangrena y necrosis del pulmón", "Respiratorio"],
  ["J85.1", "Absceso pulmonar con neumonía", "Respiratorio"],
  ["J98.1", "Colapso pulmonar", "Respiratorio"],
  ["J98.4", "Otros trastornos del pulmón", "Respiratorio"],
  ["J20.1", "Bronquitis aguda por Haemophilus influenzae", "Respiratorio"],
  ["J20.2", "Bronquitis aguda por estreptococo", "Respiratorio"],
  ["J20.3", "Bronquitis aguda por virus Coxsackie", "Respiratorio"],
  ["J20.4", "Bronquitis aguda por virus parainfluenza", "Respiratorio"],
  ["J20.6", "Bronquitis aguda por rinovirus", "Respiratorio"],
  ["J20.7", "Bronquitis aguda por virus Echo", "Respiratorio"],
  ["J20.8", "Bronquitis aguda por otros microorganismos especificados", "Respiratorio"],
  ["J21.1", "Bronquiolitis aguda por metapneumovirus humano", "Pediatría"],
  ["J43.1", "Enfisema panlobular", "Respiratorio"],
  ["J43.2", "Enfisema centrilobular", "Respiratorio"],
  ["J43.8", "Otros enfisemas", "Respiratorio"],
  ["J45.21", "Asma leve intermitente con exacerbación aguda", "Respiratorio"],
  ["J45.22", "Asma leve intermitente con estado asmático", "Respiratorio"],
  ["J45.31", "Asma leve persistente con exacerbación aguda", "Respiratorio"],
  ["J45.32", "Asma leve persistente con estado asmático", "Respiratorio"],
  ["J45.41", "Asma moderada persistente con exacerbación aguda", "Respiratorio"],
  ["J45.42", "Asma moderada persistente con estado asmático", "Respiratorio"],
  ["J45.51", "Asma severa persistente con exacerbación aguda", "Respiratorio"],
  ["J45.52", "Asma severa persistente con estado asmático", "Respiratorio"],
  ["J47.1", "Bronquiectasia con exacerbación aguda", "Respiratorio"],
  ["J47.9", "Bronquiectasia no especificada", "Respiratorio"],
  ["J96.01", "Insuficiencia respiratoria aguda con hipoxia", "Respiratorio"],
  ["J96.02", "Insuficiencia respiratoria aguda con hipercapnia", "Respiratorio"],
  ["J96.10", "Insuficiencia respiratoria crónica", "Respiratorio"],
  ["J96.11", "Insuficiencia respiratoria crónica con hipoxia", "Respiratorio"],
  ["J96.90", "Insuficiencia respiratoria no especificada", "Respiratorio"],
  ["J01.8", "Otras sinusitis agudas", "Respiratorio"],
  ["J02.8", "Faringitis aguda por otros microorganismos especificados", "Respiratorio"],
  ["J03.8", "Amigdalitis aguda por otros microorganismos especificados", "Respiratorio"],
  ["J32.8", "Otras sinusitis crónicas", "Respiratorio"],
  ["J36", "Absceso periamigdalino", "Otorrinolaringología"],
  ["J37.1", "Laringotraqueítis crónica", "Respiratorio"],
  ["J38.1", "Pólipo de las cuerdas vocales", "Otorrinolaringología"],
  ["J38.2", "Nódulos de las cuerdas vocales", "Otorrinolaringología"],
  ["E10.0", "Diabetes mellitus tipo 1 con coma", "Endocrino/Metabólico"],
  ["E10.11", "Diabetes mellitus tipo 1 con cetoacidosis y coma", "Endocrino/Metabólico"],
  ["E10.21", "Diabetes mellitus tipo 1 con nefropatía diabética", "Endocrino/Metabólico"],
  ["E10.40", "Diabetes mellitus tipo 1 con neuropatía diabética", "Endocrino/Metabólico"],
  ["E10.51", "Diabetes mellitus tipo 1 con angiopatía periférica", "Endocrino/Metabólico"],
  ["E10.65", "Diabetes mellitus tipo 1 con hiperglucemia", "Endocrino/Metabólico"],
  ["E11.22", "Diabetes mellitus tipo 2 con enfermedad renal crónica", "Endocrino/Metabólico"],
  ["E11.29", "Diabetes mellitus tipo 2 con otra complicación renal", "Endocrino/Metabólico"],
  ["E11.31", "Diabetes mellitus tipo 2 con retinopatía no proliferativa", "Endocrino/Metabólico"],
  ["E11.32", "Diabetes mellitus tipo 2 con retinopatía proliferativa", "Endocrino/Metabólico"],
  ["E11.41", "Diabetes mellitus tipo 2 con mononeuropatía", "Endocrino/Metabólico"],
  ["E11.42", "Diabetes mellitus tipo 2 con polineuropatía diabética", "Endocrino/Metabólico"],
  ["E11.43", "Diabetes mellitus tipo 2 con neuropatía autonómica", "Endocrino/Metabólico"],
  ["E11.52", "Diabetes mellitus tipo 2 con gangrena", "Endocrino/Metabólico"],
  ["E11.59", "Diabetes mellitus tipo 2 con otra complicación circulatoria", "Endocrino/Metabólico"],
  ["E11.61", "Diabetes mellitus tipo 2 con artropatía diabética", "Endocrino/Metabólico"],
  ["E11.62", "Diabetes mellitus tipo 2 con complicaciones cutáneas", "Endocrino/Metabólico"],
  ["E11.621", "Diabetes mellitus tipo 2 con úlcera del pie", "Endocrino/Metabólico"],
  ["E11.65", "Diabetes mellitus tipo 2 con hiperglucemia", "Endocrino/Metabólico"],
  ["E11.69", "Diabetes mellitus tipo 2 con otra complicación especificada", "Endocrino/Metabólico"],
  ["I13.1", "Enfermedad cardíaca y renal hipertensiva con insuficiencia renal", "Cardiovascular"],
  ["I13.9", "Enfermedad cardíaca y renal hipertensiva no especificada", "Cardiovascular"],
  ["I15.1", "Hipertensión secundaria a otros trastornos renales", "Cardiovascular"],
  ["I15.2", "Hipertensión secundaria a trastornos endocrinos", "Cardiovascular"],
  ["I15.8", "Otra hipertensión secundaria", "Cardiovascular"],
  ["I25.0", "Enfermedad cardiovascular aterosclerótica", "Cardiovascular"],
  ["I25.6", "Isquemia miocárdica silenciosa", "Cardiovascular"],
  ["I49.0", "Fibrilación y aleteo ventricular", "Cardiovascular"],
  ["I49.5", "Síndrome del seno enfermo", "Cardiovascular"],
  ["I49.8", "Otras arritmias cardíacas especificadas", "Cardiovascular"],
  ["I50.21", "Insuficiencia cardíaca sistólica aguda", "Cardiovascular"],
  ["I50.22", "Insuficiencia cardíaca sistólica crónica", "Cardiovascular"],
  ["I50.23", "Insuficiencia cardíaca sistólica aguda sobre crónica", "Cardiovascular"],
  ["I50.31", "Insuficiencia cardíaca diastólica aguda", "Cardiovascular"],
  ["I50.32", "Insuficiencia cardíaca diastólica crónica", "Cardiovascular"],
  ["I50.33", "Insuficiencia cardíaca diastólica aguda sobre crónica", "Cardiovascular"],
  ["I50.41", "Insuficiencia cardíaca combinada aguda", "Cardiovascular"],
  ["I50.42", "Insuficiencia cardíaca combinada crónica", "Cardiovascular"],
  ["I50.43", "Insuficiencia cardíaca combinada aguda sobre crónica", "Cardiovascular"],
  ["I63.0", "Infarto cerebral por trombosis de arterias precerebrales", "Neurología"],
  ["I63.1", "Infarto cerebral por embolia de arterias precerebrales", "Neurología"],
  ["I63.3", "Infarto cerebral por trombosis de arterias cerebrales", "Neurología"],
  ["I63.4", "Infarto cerebral por embolia de arterias cerebrales", "Neurología"],
  ["I63.5", "Infarto cerebral por oclusión de arterias cerebrales", "Neurología"],
  ["I63.8", "Otros infartos cerebrales", "Neurología"],
  ["I67.4", "Encefalopatía hipertensiva", "Neurología"],
  ["I80.1", "Flebitis y tromboflebitis de la vena femoral", "Cardiovascular"],
  ["I83.2", "Várices de miembros inferiores con úlcera e inflamación", "Cardiovascular"],
  ["G43.2", "Estado migrañoso", "Neurología"],
  ["G43.3", "Migraña complicada", "Neurología"],
  ["G43.4", "Migraña hemipléjica", "Neurología"],
  ["G44.3", "Cefalea crónica postraumática", "Neurología"],
  ["G44.8", "Otros síndromes de cefalea especificados", "Neurología"],
  ["G45.3", "Amaurosis fugaz", "Neurología"],
  ["G45.8", "Otras isquemias cerebrales transitorias", "Neurología"],
  ["F33.3", "Trastorno depresivo recurrente, episodio grave con síntomas psicóticos", "Salud Mental"],
  ["F32.8", "Otros episodios depresivos", "Salud Mental"],
  ["F10.0", "Intoxicación aguda por alcohol", "Salud Mental"],
  ["F10.1", "Uso nocivo de alcohol", "Salud Mental"],
  ["F10.3", "Abstinencia de alcohol", "Salud Mental"],
  ["F17.1", "Uso nocivo de tabaco", "Salud Mental"],
  ["F17.3", "Abstinencia de tabaco", "Salud Mental"],
  ["F43.8", "Otras reacciones al estrés grave", "Salud Mental"],
  ["F43.9", "Reacción al estrés grave no especificada", "Salud Mental"],
  ["K25.2", "Úlcera gástrica aguda con hemorragia y perforación", "Digestivo"],
  ["K26.1", "Úlcera duodenal aguda con perforación", "Digestivo"],
  ["K26.2", "Úlcera duodenal aguda con hemorragia y perforación", "Digestivo"],
  ["K26.6", "Úlcera duodenal crónica con hemorragia y perforación", "Digestivo"],
  ["K27.0", "Úlcera péptica aguda con hemorragia", "Digestivo"],
  ["K27.1", "Úlcera péptica aguda con perforación", "Digestivo"],
  ["K27.4", "Úlcera péptica crónica con hemorragia", "Digestivo"],
  ["K27.5", "Úlcera péptica crónica con perforación", "Digestivo"],
  ["K27.9", "Úlcera péptica no especificada sin hemorragia ni perforación", "Digestivo"],
  ["K35.0", "Apendicitis aguda con peritonitis generalizada", "Digestivo"],
  ["K35.1", "Apendicitis aguda con absceso peritoneal", "Digestivo"],
  ["K50.0", "Enfermedad de Crohn del intestino delgado", "Digestivo"],
  ["K50.1", "Enfermedad de Crohn del intestino grueso", "Digestivo"],
  ["K50.9", "Enfermedad de Crohn no especificada", "Digestivo"],
  ["K51.0", "Pancolitis ulcerativa", "Digestivo"],
  ["K51.9", "Colitis ulcerativa no especificada", "Digestivo"],
  ["K57.1", "Enfermedad diverticular del intestino delgado sin perforación ni absceso", "Digestivo"],
  ["K57.5", "Enfermedad diverticular del intestino sin perforación ni absceso", "Digestivo"],
  ["K58.2", "Síndrome de intestino irritable mixto", "Digestivo"],
  ["K58.8", "Otro síndrome de intestino irritable", "Digestivo"],
  ["K70.2", "Fibrosis hepática alcohólica", "Digestivo"],
  ["K70.4", "Insuficiencia hepática alcohólica", "Digestivo"],
  ["K74.6", "Cirrosis hepática no especificada", "Digestivo"],
  ["K76.0", "Hígado graso no alcohólico", "Digestivo"],
  ["K80.6", "Colelitiasis de vesícula y vía biliar con colecistitis", "Digestivo"],
  ["K80.8", "Otras colelitiasis", "Digestivo"],
  ["K85.0", "Pancreatitis aguda idiopática", "Digestivo"],
  ["K85.3", "Pancreatitis aguda inducida por fármacos", "Digestivo"],
  ["K85.8", "Otras pancreatitis agudas", "Digestivo"],
  ["K86.0", "Pancreatitis crónica alcohólica", "Digestivo"],
  ["K92.0", "Hematemesis", "Digestivo"],
  ["K92.1", "Melena", "Digestivo"],
  ["K92.2", "Hemorragia gastrointestinal no especificada", "Digestivo"],
  ["N11.0", "Pielonefritis crónica no obstructiva con reflujo", "Genitourinario"],
  ["N11.1", "Pielonefritis crónica obstructiva", "Genitourinario"],
  ["N11.8", "Otras nefritis tubulointersticiales crónicas", "Genitourinario"],
  ["N13.2", "Hidronefrosis por cálculo renal o ureteral", "Genitourinario"],
  ["N13.6", "Pionefrosis", "Genitourinario"],
  ["N18.31", "Enfermedad renal crónica estadio 3a", "Genitourinario"],
  ["N18.32", "Enfermedad renal crónica estadio 3b", "Genitourinario"],
  ["N34.1", "Uretritis no específica", "Genitourinario"],
  ["N34.2", "Otras uretritis", "Genitourinario"],
  ["N41.3", "Prostatocistitis", "Genitourinario"],
  ["N41.9", "Prostatitis no especificada", "Genitourinario"],
  ["N48.1", "Balanopostitis", "Genitourinario"],
  ["M05.1", "Enfermedad reumatoide del pulmón", "Musculoesquelético"],
  ["M06.1", "Enfermedad de Still del adulto", "Musculoesquelético"],
  ["M06.8", "Otras artritis reumatoides especificadas", "Musculoesquelético"],
  ["M08.0", "Artritis reumatoide juvenil", "Musculoesquelético"],
  ["M08.3", "Poliartritis juvenil", "Pediatría"],
  ["M08.4", "Artritis juvenil pauciarticular", "Pediatría"],
  ["M08.9", "Artritis juvenil no especificada", "Pediatría"],
  ["M10.2", "Gota inducida por fármacos", "Musculoesquelético"],
  ["M13.0", "Poliartritis no especificada", "Musculoesquelético"],
  ["M13.9", "Artritis no especificada", "Musculoesquelético"],
  ["M15.0", "Artrosis primaria generalizada", "Musculoesquelético"],
  ["M15.4", "Artrosis erosiva", "Musculoesquelético"],
  ["M15.9", "Poliartrosis no especificada", "Musculoesquelético"],
  ["M16.4", "Coxartrosis bilateral postraumática", "Musculoesquelético"],
  ["M16.5", "Coxartrosis postraumática", "Musculoesquelético"],
  ["M17.2", "Gonartrosis bilateral postraumática", "Musculoesquelético"],
  ["M17.3", "Gonartrosis postraumática", "Musculoesquelético"],
  ["M17.4", "Gonartrosis secundaria bilateral", "Musculoesquelético"],
  ["M17.5", "Gonartrosis secundaria", "Musculoesquelético"],
  ["M19.0", "Artrosis primaria de otras articulaciones", "Musculoesquelético"],
  ["M19.1", "Artrosis postraumática de otras articulaciones", "Musculoesquelético"],
  ["M19.2", "Artrosis secundaria de otras articulaciones", "Musculoesquelético"],
  ["M47.2", "Espondilosis con radiculopatía", "Musculoesquelético"],
  ["M47.9", "Espondilosis no especificada", "Musculoesquelético"],
  ["M50.0", "Trastorno de disco cervical con mielopatía", "Musculoesquelético"],
  ["M50.2", "Desplazamiento de disco cervical", "Musculoesquelético"],
  ["M50.9", "Trastorno de disco cervical no especificado", "Musculoesquelético"],
  ["M51.9", "Trastorno de disco intervertebral no especificado", "Musculoesquelético"],
  ["M54.16", "Radiculopatía lumbar", "Musculoesquelético"],
  ["M54.17", "Radiculopatía lumbosacra", "Musculoesquelético"],
  ["M51.16", "Trastorno de disco lumbar con radiculopatía", "Musculoesquelético"],
  ["L20.0", "Dermatitis atópica, prurigo de Besnier", "Dermatología"],
  ["L21.9", "Dermatitis seborreica no especificada", "Dermatología"],
  ["L23.2", "Dermatitis alérgica de contacto por cosméticos", "Dermatología"],
  ["L23.5", "Dermatitis alérgica de contacto por productos químicos", "Dermatología"],
  ["L24.9", "Dermatitis de contacto por irritantes no especificada", "Dermatología"],
  ["L25.9", "Dermatitis de contacto no especificada", "Dermatología"],
  ["L28.0", "Liquen simple crónico", "Dermatología"],
  ["L29.9", "Prurito no especificado", "Dermatología"],
  ["L30.1", "Dishidrosis", "Dermatología"],
  ["L30.4", "Eritema intertrigo", "Dermatología"],
  ["L30.5", "Pitiriasis alba", "Dermatología"],
  ["L50.5", "Urticaria colinérgica", "Dermatología"],
  ["L71.9", "Rosácea no especificada", "Dermatología"],
  ["L73.2", "Hidradenitis supurativa", "Dermatología"],
  ["B00.1", "Dermatitis vesicular herpética", "Dermatología"],
  ["B00.2", "Gingivoestomatitis herpética", "Infecciosas"],
  ["B01.0", "Meningitis por varicela", "Infecciosas"],
  ["B01.8", "Varicela con otras complicaciones", "Infecciosas"],
  ["B02.0", "Encefalitis por herpes zóster", "Infecciosas"],
  ["B02.7", "Herpes zóster diseminado", "Infecciosas"],
  ["B02.8", "Herpes zóster con otras complicaciones", "Infecciosas"],
  ["B05.2", "Sarampión complicado con neumonía", "Pediatría"],
  ["B05.3", "Sarampión complicado con otitis media", "Pediatría"],
  ["B05.8", "Sarampión con otras complicaciones", "Pediatría"],
  ["B06.9", "Rubéola sin complicación", "Pediatría"],
  ["B26.0", "Orquitis por parotiditis", "Infecciosas"],
  ["B26.1", "Meningitis por parotiditis", "Infecciosas"],
  ["B26.3", "Pancreatitis por parotiditis", "Infecciosas"],
  ["B26.8", "Parotiditis con otras complicaciones", "Infecciosas"],
  ["A15.1", "Tuberculosis pulmonar confirmada por cultivo", "Infecciosas"],
  ["A15.2", "Tuberculosis pulmonar confirmada por histología", "Infecciosas"],
  ["A16.0", "Tuberculosis pulmonar con baciloscopia y cultivo negativos", "Infecciosas"],
  ["A16.1", "Tuberculosis pulmonar sin examen bacteriológico", "Infecciosas"],
  ["A16.5", "Pleuritis tuberculosa sin confirmación", "Infecciosas"],
  ["A97.9", "Dengue no especificado", "Infecciosas"],
  ["E06.0", "Tiroiditis aguda", "Endocrino/Metabólico"],
  ["E06.1", "Tiroiditis subaguda", "Endocrino/Metabólico"],
  ["E06.4", "Tiroiditis inducida por fármacos", "Endocrino/Metabólico"],
  ["E07.9", "Trastorno de la tiroides no especificado", "Endocrino/Metabólico"],
  ["E66.1", "Obesidad inducida por fármacos", "Endocrino/Metabólico"],
  ["E66.8", "Otras obesidades", "Endocrino/Metabólico"],
  ["E78.4", "Otra hiperlipidemia", "Endocrino/Metabólico"],
  ["E78.9", "Trastorno del metabolismo de las lipoproteínas no especificado", "Endocrino/Metabólico"],
  ["H00.1", "Chalazión", "Oftalmología"],
  ["H04.2", "Epífora", "Oftalmología"],
  ["H16.0", "Úlcera de la córnea", "Oftalmología"],
  ["H25.9", "Catarata senil no especificada", "Oftalmología"],
  ["H26.9", "Catarata no especificada", "Oftalmología"],
  ["H40.1", "Glaucoma primario de ángulo abierto", "Oftalmología"],
  ["H40.2", "Glaucoma primario de ángulo cerrado", "Oftalmología"],
  ["H40.9", "Glaucoma no especificado", "Oftalmología"],
  ["H52.0", "Hipermetropía", "Oftalmología"],
  ["H60.0", "Absceso del oído externo", "Otorrinolaringología"],
  ["H60.1", "Celulitis del oído externo", "Otorrinolaringología"],
  ["H60.9", "Otitis externa no especificada", "Otorrinolaringología"],
  ["H66.4", "Otitis media supurativa no especificada", "Otorrinolaringología"],
  ["N76.0", "Vaginitis aguda", "Ginecología"],
  ["N80.2", "Endometriosis de la trompa de Falopio", "Ginecología"],
  ["N80.3", "Endometriosis del peritoneo pélvico", "Ginecología"],
  ["N83.1", "Quiste del cuerpo lúteo", "Ginecología"],
  ["N91.0", "Amenorrea primaria", "Ginecología"],
  ["N91.1", "Amenorrea secundaria", "Ginecología"],
  ["N92.2", "Menstruación excesiva en la pubertad", "Ginecología"],
  ["N94.1", "Dispareunia", "Ginecología"],
  ["N95.0", "Hemorragia posmenopáusica", "Ginecología"],
  ["N95.2", "Vaginitis atrófica posmenopáusica", "Ginecología"],
  ["O21.9", "Hiperémesis gravídica no especificada", "Obstetricia"],
  ["O23.4", "Infección urinaria en el embarazo", "Obstetricia"],
  ["O42.0", "Ruptura prematura de membranas con trabajo de parto en 24 horas", "Obstetricia"],
  ["O42.9", "Ruptura prematura de membranas no especificada", "Obstetricia"],
  ["O48", "Embarazo prolongado", "Obstetricia"],
  ["O60.1", "Trabajo de parto prematuro con parto prematuro", "Obstetricia"],
  ["O70.0", "Desgarro perineal de primer grado durante el parto", "Obstetricia"],
  ["O70.1", "Desgarro perineal de segundo grado durante el parto", "Obstetricia"],
  ["O72.0", "Hemorragia del tercer período del parto", "Obstetricia"],
  ["O72.1", "Hemorragia posparto inmediata", "Obstetricia"],
  ["O80.0", "Parto único espontáneo en presentación cefálica", "Obstetricia"],
  ["O80.1", "Parto único espontáneo en presentación podálica", "Obstetricia"],
  ["O82.0", "Cesárea electiva", "Obstetricia"],
  ["O82.1", "Cesárea de emergencia", "Obstetricia"],
  ["D50.0", "Anemia ferropénica por pérdida de sangre", "Hematología"],
  ["D50.8", "Otras anemias por deficiencia de hierro", "Hematología"],
  ["D64.8", "Otras anemias especificadas", "Hematología"],
  ["D69.3", "Púrpura trombocitopénica idiopática", "Hematología"],
  ["R10.0", "Abdomen agudo", "Síntomas y Signos"],
  ["R10.3", "Dolor en la parte inferior del abdomen", "Síntomas y Signos"],
  ["R50.0", "Fiebre con escalofrío", "Síntomas y Signos"],
  ["R06.4", "Hiperventilación", "Síntomas y Signos"],
  ["R07.1", "Dolor torácico al respirar", "Síntomas y Signos"],
  ["U09.9", "Condición posterior a COVID-19", "Infecciosas"],
];
